package com.ogame.ogamestats.repository;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import com.ogame.ogamestats.entity.Player;
import com.ogame.ogamestats.repository.IPlayerRepository;

@ExtendWith(SpringExtension.class)
@DataJpaTest
public class PlayerRepositoryIntegrationTest {

	@Autowired
	private TestEntityManager entityManager;
	
	@Autowired
	private IPlayerRepository playerRepository;

	@Test
	public void whenFindPlayer() {
		Player p = new Player();
		// No put this value, it is autogenerated
		//p.setId(1);
		p.setIdplayer("UK123456789");
		p.setName("Jordi");
		
		entityManager.persist(p);
		entityManager.flush();
		
		Player result = playerRepository.findById(1);
		
		assertThat(p.getIdplayer()).isEqualTo(result.getIdplayer());
	}
}
